const { Wallet } = require('./index');
const { ChainUtil } = require('../chain-util');
const { Transaction } = require('./transaction');
console.log(Transaction);
console.log(ChainUtil);
const { TransactionPool } = require('./trasnaction-pool.js');
let transaction, wallet, recepient, amount, Trans, w;
wallet = new Wallet();
w = new Wallet();
amount = 50;
recepient = 'recep';
let pool = new TransactionPool();
transaction = wallet.createTransaction(recepient, amount, pool);
wallet.createTransaction(recepient, 222, pool);
console.log(pool);
w.createTransaction(recepient, amount, pool);
console.log(pool + '\n\n\n\n');
pool = pool.validTransactions();
console.log(pool);
